### ISSUE TITLE
Docker Desktop failed to start after adding a path starting with a space in the File Sharing Settings

### ISSUE THREAD

**Issue by cheack** [docker/desktop-linux#122]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4642e174-7abf-4972-9c7b-b0a59e52e1eb/20230209081950

### Expected behavior
The path to be added is automatically stripped of any extra spaces and Docker Desktop successfully started.
### Actual behavior
`Docker Desktop stopped...` message.
### Information

  - Linux distro: Linux Mint
  - Distro version: 21.1 Vera
  - Docker Desktop Version: 4.16.1 (95567)

### Steps to reproduce the behavior

  1. Open File Sharing Settings, manually type a path starting with a space, ` /snap/phpstorm` in my case, hit Enter.
  2. Apply & Restart

The workaround is to edit the added path in `/home/$USER/.docker/desktop/settings.json` and restart Docker Desktop:
```
"filesharingDirectories": [
  " /snap/phpstorm",   ----- removing the leading space solves the problem
  "/home"
],
```

**Comment by aiordache** [comment]
@cheack Thanks for raising the issue. It should be fixed in the next release 4.17.

**Comment by TahaDgn** [comment]
@aiordache, Seems like the problem still goes in Linux Mint vera. When I try to update it tru GUI it is resisting to not saving it. On the other hand, it ends by crashing/breaking docker-desktop when I changed it manually by the given path.

V 4.22.0
