### ISSUE TITLE
Docker Desktop is not starting properly.

### ISSUE THREAD

**Issue by coyoteXujie** [docker/desktop-linux#250]
### Description

running engine: waiting for the VM setup to be ready: running filesharing: running virtiofsd for /home: exit status 101

### Reproduce

/opt/docker-desktop/bin/docker-desktop

### docker version

```bash
Client:
 Version:           19.03.0-dev
 API version:       1.40
 Go version:        go1.15.9
 Git commit:        
 Built:             Thu Dec  9 02:13:10 2021
 OS/Arch:           linux/amd64
 Experimental:      false
```

### docker info

```bash
Client:
 Debug Mode: false
 Plugins:
  debug: Get a shell into any image or container (Docker Inc., 0.0.34)
  desktop: Docker Desktop commands (Alpha) (Docker Inc., v0.0.14)
  dev: Docker Dev Environments (Docker Inc., v0.1.2)
  feedback: Provide feedback, right in your terminal! (Docker Inc., v1.0.5)
  scout: Docker Scout (Docker Inc., v1.11.0)
  buildx: Docker Buildx (Docker Inc., v0.16.1-desktop.1)
  compose: Docker Compose (Docker Inc., v2.29.1-desktop.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.25)
  init: Creates Docker-related starter files for your project (Docker Inc., v1.3.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///home/jie/.docker/desktop/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

63F454D7-C835-409E-B1F9-98F7187A0EB1/20240915100805

**Comment by jpbriend** [comment]
@coyoteXujie can you try to download and install latest version (`4.34` but `4.35` is expected in a few days)?
Many bugs have been solved regarding virtio (the culprit in your  VM failing to successfully start).

**Comment by coyoteXujie** [comment]
Hello, the latest version of docker-desktop is 4.34.2, still having the same problem, do I need to wait until 4.35 is released, and what is the approximate time for 4.35 to be released?




草原狼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "docker/desktop-linux"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [docker/desktop-linux] Docker Desktop is not starting properly. (Issue #250)






@coyoteXujie can you try to download and install latest version (4.34 but 4.35 is expected in a few days)?
Many bugs have been solved regarding virtio (the culprit in your  VM failing to successfully start).
